### ISSUE TITLE
dist/dd-manager.js not exist after npm install

### ISSUE THREAD

**Issue by iegik** [driveback/digital-data-manager#43]
I add `npm install --save ssh+git://github.com/driveback/digital-data-manager.git#1.1.5` as dependency to my project.

package.json main section contains `"dist/dd-manager.js"` but file not exists in repository.

---

Remove "main" from package.json or keep dist folder in repository.

**Comment by yurevichcv** [comment]
@iegik 

> Remove "main" from package.json or keep dist folder in repository.

 which variant do you prefer?

**Comment by iegik** [comment]
Remove "main" from package.json
