### ISSUE TITLE
Как сохранять информацию о пользователях в CRM?

### ISSUE THREAD

**Issue by Evil1991** [driveback/digital-data-manager#46]
Собственно сабж, не нашел ответа

**Comment by iegik** [comment]
Выдёргивать данные из [digitalData.user](https://ddmanager.readme.io/docs/object-definitions#user). За вами (CRM) ответ на вопрос - "Когда?".

**Comment by yurevichcv** [comment]
Привет, сам процесс сохранения в CRM никак не регламентирован и остается на стороне разработчиков сайта. Важно понимать, когда именно и какие данные должны быть переданы в CRM.

Например, пользователь подписался на рассылку в каком-то блоке сайта и выбрал какие-то опции (например - пол). В DDL отправляется событие:

```
digitalData.events.push({
  name: 'Subscribed',
  user: {
    email: 'test@email.com',
    gender: 'male'
  }
});
```

Далее, необходимо подписаться на это событие (например в GTM) и сохранить данные в CRM:

```
ddListener.push(['on', 'event', function(event) {
  if (event.name === 'Subscribed') {
      // сохранить значения event.user.email и event.user.gender в CRM
  }
}]);
```

**Comment by Evil1991** [comment]
Спасибо за ответ! Подскажите еще, где DDL хранит всю информацию? В localStorage? И создаются какие-то уникальные пользовательские ID для синхронизации информации с CRM?

**Comment by iegik** [comment]
`window.digitalData` https://github.com/driveback/digital-data-manager/blob/master/src/ddManager.js#L21

**Comment by Evil1991** [comment]
А она в свою очередь где хранится? в localstorage?

**Comment by iegik** [comment]
Это переменнаф JavaScript. Она обьявлена глобально `var digitalData = ...` или `window.digitalData = ..`
В памяти компьютера. См. как работает JavaScript.

**Comment by Evil1991** [comment]
а при переходе между страницами? она разве не сотрется?

**Comment by iegik** [comment]
**На сколько я понимаю**, задача DigitalData - единообразно структурировать данные и перенаправлять (мапить) эти данные на другие сервисы, где в каждом есть свой обьект данных, хронящийся по-своему.
Например, в GTM - dataLayer имеет схожую структуру. А как он работает, расскажет больше документация Google.
Идея одна - при изменении данных вызывается событие, которое отправляет данные сразу (синхронно) или переодически (асинхронно) на свой сервис, где и собирается и обробатывается вся информация.
Пример запроса: https://www.google-analytics.com/r/collect?v=1&_v=j46&a=123&t=event&ni=1&_s=1&dl=http://example.com

**Comment by yurevichcv** [comment]
@Evil1991 Данные нигде не хранятся. DigitalData - это слой агрегации данных и роутинга их в другие системы через единый API. В случае, если вы хотите сохранить какие-то данные, чтобы использовать их на других страницах, необходимо воспользоваться cookies или localStorage.
