### ISSUE TITLE
Content  Searched  User used search  ✓ Is sent automatically if digitalData.page.type equals to "search"

### ISSUE THREAD

**Issue by iegik** [driveback/digital-data-manager#47]
Утверждение не верно. https://ddmanager.readme.io/docs/semantic-events
```
{
    "version": "1.1.1",
    "page":{
        "type":"search",
        ...
    },
    ...
}
```

События, которые выполнились автоматически:

- DDL snapshot:
- Event: Viewed Page

**Comment by yurevichcv** [comment]
Для того, чтобы было отправлено событие - нужно, чтобы на странице присутствовал объект digitalData.listing.

Для большей прозрачности мы не рекомендуем использовать autoEvents:true. Мало того, в будущих версиях она станет deprecated. Таким образом, лучше всего все события отправлять вручную (на сайте или через GTM).

Обновленную документацию (на примере интеграции GA) можно найти тут - https://digitaldata.readme.io/docs/google-analytics

**Comment by yurevichcv** [comment]
Лучше использовать русскую версию документации. На текущий момент она обновляется оперативнее.

**Comment by yurevichcv** [comment]
Таким образом, страница просмотра результатов поиска должна выглядеть примерно так:

```
window.digitalData = {
    "version": "1.1.1",
    "page":{
        "type":"search",
        ...
    },
    "listing: {
       "query": "<search query>"
    }
};

digitalData.events.push({
   "name": "Viewed Page",
   "page": digitalData.page
});

digitalData.events.push({
   "name": "Searched Products",
   "listing": digitaData.listing
});
```

**Comment by iegik** [comment]
Заполнение следующий полей решило проблему:
```
window.digitalData.page.type = "search";
window.digitalData.listing.query = "";
```
