### ISSUE TITLE
Rees46 support

### ISSUE THREAD

**Issue by temoffey** [driveback/digital-data-manager#54]
Do you plan to expand the list of supported meters. Specifically interested Rees46 (https://rees46.com/).
If not, I get some advice on the possible addition of self-support count in digital-data-manager?

**Comment by tsmirnov** [comment]
Hi, @temoffey. Yes, we have Rees46 in our plans, but don't know when exactly we start. But you are always welcome for pull request ;)

**Comment by temoffey** [comment]
Then I have the following question:
how the assembly of all files in the /src into a single file /distr?

**Comment by yurevichcv** [comment]
Hi, use the following command:
```
npm run dist
```
